# Install the probe-rs testcandidate repository
name: Install testcandidate
description: Install the probe-rs testcandidate
inputs:
  ref:
    description: "The ref to clone"
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup probe-rs testcandidate
      - uses: actions/checkout@v3
        with:
          repository: probe-rs/probe-rs
          ref: ${{ inputs.ref }}
          path: probe-rs-hive-testcandidate