[package]
name = "comm-types"
version = "0.1.0"
edition = "2021"
authors = ["TeyKey1"]
repository = "https://github.com/probe-rs/hive-software"
description = "Common types used for communication between Hive applications"
readme = "README.md"

[features]
hardware = []

[dependencies]
serde = { version = "1.0", features = ["derive"] }
