# Format code

on:
  push:
    branches: [master, staging, trying]
  pull_request:
  merge_group:

jobs:
  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup probe-rs testcandidate
        uses: actions/checkout@v3
        with:
          repository: probe-rs/probe-rs
          ref: v0.18.0
          path: probe-rs-hive-testcandidate

      # workaround as actions/checkout cannot clone outside of workspace
      - name: Move probe-rs testcandidate
        run: mv probe-rs-hive-testcandidate ../

      - name: Run cargo fmt
        run: cargo fmt --all -- --check