# Run clippy, check and deny

on:
  push:
    branches: [master, staging, trying]
  pull_request:
  merge_group:


name: Run linter and check

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - uses: ./.github/actions/setup

      # Check monitor separately as the build needs to happen separately due to conflict of probe-rs with probe-rs-test
      - name: cargo check monitor
        run: cargo check --all-features --locked -p monitor

      - name: debug
        run: cat Cargo.lock

      - name: cargo check others
        run: cargo check --workspace --all-features --locked --exclude monitor

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - uses: ./.github/actions/setup
        with:
          components: clippy

      - name: Run cargo clippy
        run: cargo clippy --all-features --locked -- -D warnings

#  cargo-deny:
#    name: Deny
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout sources
#        uses: actions/checkout@v3
#
#      - name: Setup probe-rs testcandidate
#        uses: actions/checkout@v3
#        with:
#          repository: probe-rs/probe-rs
#          ref: v0.20.0
#          path: probe-rs-hive-testcandidate
#
#      # workaround as actions/checkout cannot clone outside of workspace
#      - name: Move probe-rs testcandidate
#        run: mv probe-rs-hive-testcandidate ../
#
#      - uses: EmbarkStudios/cargo-deny-action@v1