# Run tests

on:
  push:
    branches: [master, staging, trying]
  pull_request:
  merge_group:

name: Run tests

jobs:
  test:
    name: Rust
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - uses: ./.github/actions/setup

      # Test monitor separately as the build needs to happen separately due to conflict of probe-rs with probe-rs-test
      - name: cargo test monitor
        run: cargo test --all-features -p monitor

      - name: cargo test others
        run: cargo test --workspace --all-features --exclude monitor --exclude hive --exclude controller --no-fail-fast # excluding controller for now due to optional probe-rs deps not making it possible to build (tracking issue: https://github.com/rust-lang/cargo/issues/2911)

  # Special test-case hive CLI, which needs to build/run on win, linux and mac
  test-hive-cli:
    name: Rust (hive CLI)
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - uses: ./.github/actions/setup

      - name: cargo test hive
        run: cargo test --all-features -p hive
