# Run tests

on:
  push:
    branches: [master, staging, trying]
  pull_request:
  merge_group:

jobs:
  test:
    name: Rust tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup probe-rs testcandidate
        uses: actions/checkout@v3
        with:
          repository: probe-rs/probe-rs
          ref: v0.18.0
          path: probe-rs-hive-testcandidate

      # workaround as actions/checkout cannot clone outside of workspace
      - name: Move probe-rs testcandidate
        run: mv probe-rs-hive-testcandidate ../

      - name: Install libusb (linux)
        run: |
          sudo apt update
          sudo apt install -y libusb-1.0-0-dev libudev-dev
      
      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2.4.0

      # Test monitor separately as the build needs to happen separately due to conflict of probe-rs with probe-rs-test
      - name: cargo test monitor
        run: cargo test --all-features --locked -p monitor

      - name: cargo test others
        run: cargo test --workspace --all-features --locked --exclude monitor --no-fail-fast