//! Types used in IPC between runner and monitor

use serde::{Deserialize, Serialize};

use super::hardware::{ProbeInfo, TargetState};

/// All possible message types that can be sent via Hive IPC
#[derive(Debug, Serialize, Deserialize)]
pub enum IpcMessage {
    /// Information on the connected probes required by the runner
    ProbeInitData([Option<ProbeInfo>; 4]),
    /// Information on the connected targets required by the runner
    TargetInitData([Option<[TargetState; 4]>; 8]),
    /// Log generated by the runner on a test run
    RunnerLog,
    /// Test results generated by the runner
    TestResults,
    /// Generic Ipc error, in case of wrong requests, etc
    IpcError(String),
    /// Desync error returned by runner, in case the received probe and target data does not seem to match the hardware detected by the runner
    DesyncError,
}
